<a href="https://colab.research.google.com/github/JnLuck/PracticeNumPy/blob/main/pr%C3%A1cticaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importar NumPy**

In [1]:
#Importamos a libreria numpy de python
import numpy as np

**1. Creación de Arrays**

**1.1**

In [7]:
#Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
vector = np.array([7, 12, 17, 27, 30])

# Mostrar el vector
print(vector)

[ 7 12 17 27 30]


**1.2**

In [6]:
#Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
matriz = np.arange(1, 10).reshape(3, 3)

# Mostrar la matriz
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**1.3**

In [11]:
#Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
matriz_z = np.zeros([2,4],int)

# Mostrar la matriz
print(matriz_z)

[[0 0 0 0]
 [0 0 0 0]]


**1.4**

In [12]:
#Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
matriz_one = np.ones([3,2],int)

# Mostrar la matriz
print(matriz_one)

[[1 1]
 [1 1]
 [1 1]]


**1.5**

In [14]:
#Utiliza la función np.random.randint() para crear una matriz
#de tamaño 4x4 con números enteros aleatorios entre 0 y 10
matriz_random = np.random.randint(0, 11, size=(4, 4))

# Mostrar la matriz
print(matriz_random)

[[6 4 3 6]
 [7 3 4 9]
 [6 6 6 0]
 [3 4 7 6]]


**2. Acceso a Elementos**

**2.1**

In [75]:
#Accede al tercer elemento del vector creado en el paso 1.
# Mostrar el vector
print(vector)
print()

tercer_elemento = vector[2]

# Mostrar el tercer elemento
print("El tercer elemento del vector es:", tercer_elemento)

[ 7 12 17 27 30]

El tercer elemento del vector es: 17


**2.2**

In [71]:
#Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2.
print(matriz)
print()

elemento = matriz[1, 1]  # Fila 1, columna 1 (recordando que los índices comienzan en 0)

# Mostrar el elemento seleccionado
print("Elemento:", elemento)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemento: 5


**3. Propiedades de los Arrays**

**3.1**

In [70]:
#Utiliza el atributo ndim para verificar la cantidad de dimensiones
#de la matriz creada en el paso 2
print(matriz)
print()

numero_de_dimensiones = matriz.ndim

# Mostrar la cantidad de dimensiones de la matriz
print("Número de dimensiones:", numero_de_dimensiones)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Número de dimensiones: 2


**3.2**

In [69]:
#Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
print(matriz)
print()

forma = matriz.shape

# Mostrar la forma de la matriz
print("Forma de la matriz:", forma)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Forma de la matriz: (3, 3)


**3.3**

In [68]:
#Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.
print(matriz)
print()

tamaño_total = matriz.size

# Mostrar el tamaño total de la matriz
print("Tamaño total:", tamaño_total)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Tamaño total: 9


**4. Operaciones Básicas**

**4.1**

In [33]:
#Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
matriz1 = np.random.randint(0, 11, size=(2, 2))
matriz2 = np.random.randint(0, 11, size=(2, 2))

# Sumar las dos matrices
suma_matrices = matriz1 + matriz2

# Mostrar las matrices y su suma
print("Matriz 1:")
print(matriz1)
print()
print("Matriz 2:")
print(matriz2)
print()
print("Suma de las matrices:")
print(suma_matrices)

Matriz 1:
[[5 2]
 [1 5]]

Matriz 2:
[[4 1]
 [8 2]]

Suma de las matrices:
[[9 3]
 [9 7]]


**4.2**

In [41]:
#Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
# Crear una matriz de tamaño 3x2 con valores aleatorios
matriz1 = np.array([[1,2],[3,4],[5,6]])

# Crear una matriz de tamaño 2x3 con valores aleatorios
matriz2 = np.array([[7,8,9],[10,11,12]])

# Multiplicar las dos matrices
resultado_multiplicacion = np.dot(matriz1, matriz2)

# Mostrar las matrices y el resultado de la multiplicación
print("Matriz 1 (3x2):")
print(matriz1)
print()
print("Matriz 2 (2x3):")
print(matriz2)
print()
print("Resultado de la multiplicación (3x3):")
print(resultado_multiplicacion)

Matriz 1 (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matriz 2 (2x3):
[[ 7  8  9]
 [10 11 12]]

Resultado de la multiplicación (3x3):
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


**4.3**

In [32]:
#Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2,utilizando
#tanto la división por elementos como la multiplicación por la inversa.
matriz1 = np.random.randint(1, 11, size=(2, 2))
matriz2 = np.random.randint(1, 11, size=(2, 2))

# División por elementos
division_elementos = matriz1 / matriz2

# División mediante multiplicación por la inversa de la segunda matriz
# Comprobar primero si la matriz es invertible
if np.linalg.det(matriz2) != 0:
    inversa_matriz2 = np.linalg.inv(matriz2)
    division_inversa = np.dot(matriz1, inversa_matriz2)
else:
    division_inversa = "La matriz 2 no es invertible"

# Mostrar resultados
print("Matriz 1:")
print(matriz1)
print()
print("Matriz 2:")
print(matriz2)
print()
print("División por elementos:")
print(division_elementos)
print()
print("División por la inversa de la matriz 2:")
print(division_inversa)

Matriz 1:
[[5 9]
 [7 6]]

Matriz 2:
[[ 6 10]
 [ 3  2]]

División por elementos:
[[0.83333333 0.9       ]
 [2.33333333 3.        ]]

División por la inversa de la matriz 2:
[[ 0.94444444 -0.22222222]
 [ 0.22222222  1.88888889]]


**5. Manipulación de Arrays**

**5.1**

In [58]:
#Utiliza la función reshape() para convertir el vector creado en el paso 2
#en una matriz de tamaño 9x1.
print(matriz)
print()

matriz_9x1 = matriz.reshape((9, 1))

# Mostrar la nueva matriz de tamaño 9x1
print("Matriz convertida a tamaño 9x1:")
print(matriz_9x1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz convertida a tamaño 9x1:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**5.2**

In [55]:
#Utiliza la función flatten() para convertir la matriz creada en el paso 2
#en un vector unidimensional.
print(matriz)
print()

vector_unidimensional = matriz.flatten()

# Mostrar el vector resultante
print("Vector unidimensional:")
print(vector_unidimensional)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector unidimensional:
[1 2 3 4 5 6 7 8 9]


**6. Operaciones Estadísticas**

**6.1**

In [57]:
# Calcula la suma de todos los elementos de la matriz creada en el paso 2.
print(matriz)
print()

suma_elementos = matriz.sum()

# Mostrar la suma de los elementos
print("Suma:", suma_elementos)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Suma: 45


**6.2**

In [59]:
#Calcula la media de cada fila de la matriz creada en el paso 2.
print(matriz)
print()

# Calcular la media de cada fila de la matriz
media_filas = matriz.mean(axis=1)

# Mostrar la media de cada fila
print("Media de cada fila:")
print(media_filas)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Media de cada fila:
[2. 5. 8.]


**7. Indexación y Rebanado**

**7.1**

In [62]:
#Imprime la primera fila de la matriz creada en el paso 2.
print(matriz)
print()

# Imprimir la primera fila de la matriz
print("Primera fila de la matriz:")
print(matriz[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Primera fila de la matriz:
[1 2 3]


**7.2**

In [63]:
#Imprime las primeras dos columnas de la matriz creada en el paso 2.
print(matriz)
print()

# Imprimir las primeras dos columnas de la matriz
print("Primeras dos columnas de la matriz:")
print(matriz[:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Primeras dos columnas de la matriz:
[[1 2]
 [4 5]
 [7 8]]


**8. Ejercicio Adicional**

**8.1**

In [64]:
#Escribe un código para encontrar el valor máximo y mínimo de la matriz,
#así como su posición.

Matriz de 4x4 con valores flotantes aleatorios:
[[0.66639291 0.66275765 0.25216839 0.85657232]
 [0.85959221 0.00953036 0.88645488 0.90521861]
 [0.50153767 0.88428396 0.85490067 0.96857272]
 [0.0687318  0.26920747 0.44597335 0.47103154]]


**8.2**

In [67]:
#Define una matriz de tamaño 4x4 con valores aleatorios
# Mostrar la matriz
print("Matriz de 4x4 con valores aleatorios:")
print(matriz_aleatoria)
print()
# Encontrar el valor máximo y su posición
valor_maximo = np.max(matriz_aleatoria)
posicion_maximo = np.unravel_index(np.argmax(matriz_aleatoria), matriz_aleatoria.shape)

# Encontrar el valor mínimo y su posición
valor_minimo = np.min(matriz_aleatoria)
posicion_minimo = np.unravel_index(np.argmin(matriz_aleatoria), matriz_aleatoria.shape)

# Mostrar los valores y posiciones
print(f"El valor máximo es {valor_maximo} y se encuentra en la posición {posicion_maximo}")
print(f"El valor mínimo es {valor_minimo} y se encuentra en la posición {posicion_minimo}")

Matriz de 4x4 con valores aleatorios:
[[0.66639291 0.66275765 0.25216839 0.85657232]
 [0.85959221 0.00953036 0.88645488 0.90521861]
 [0.50153767 0.88428396 0.85490067 0.96857272]
 [0.0687318  0.26920747 0.44597335 0.47103154]]

El valor máximo es 0.9685727208073673 y se encuentra en la posición (2, 3)
El valor mínimo es 0.0095303604819299 y se encuentra en la posición (1, 1)
